asct/urls.py
from django.urls import path
from . import views

# apps/asct/
app_name = 'asct'

urlpatterns = [
    path('', views.asct_home, name='index'),
    # path('create/', views.blog_create, name='post-create'),
    # path('<int:pk>/update', views.blog_update, name='post-update'),
    # path('<int:pk>/delete', views.blog_delete, name='post-delete'),
    # path('<int:pk>/detail', views.blog_detail, name='post-detail'),
    # path('<str:username>/user-posts', views.blog_user_posts, name='user-posts'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from asct import views as asct_views
from todos import views as todos_views
import debug_toolbar

admin.site.site_header = "ASCT 관리자 페이지" # H1 헤더 및 로그인 양식 상단 텍스트
admin.site.site_title = "Automated System Check Tool" # 브라우저 페이지 <title> 태그 접미사
admin.site.index_title = "관리자 대시보드에 오신 것을 환영합니다" 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('', todos_views.index, name='main-home'),
    path('apps/idols/', include('idols.urls')),
    path('apps/blog/', include('blog.fbv_urls')),
    path('apps/asct/', include('asct.urls')),
    path('apps/store/', include('store.urls')),
    path('apps/library/', include('library.urls')),
    path('apps/polls/', include('polls.urls')),
    path('apps/events/', include('events.urls')),
    path('apps/todos/', include('todos.urls')),
    path('docs/', include('docs.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# '/'를 '/app/library/'로 redirect 함
# urlpatterns += [
#     path('', RedirectView.as_view(url='/apps/library/', permanent=True))
# ]

todos/urls.py
from django.urls import path
from . import views

app_name = 'todos'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:year>/<int:month>/', views.index, name='index'),
    path('list/', views.todo_list, name='list'),
    path('create/', views.create, name='create'),
    path('update/<int:todo_id>/', views.update, name='update'),
    path('delete/<int:todo_id>/', views.delete, name='delete'),
    path('detail/<int:todo_id>/', views.detail, name='detail'),
]

todos/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField

class Todo(models.Model):
    title = models.CharField(max_length=200)
    content = RichTextUploadingField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    start_date = models.DateTimeField(blank=True, null=True)
    end_date = models.DateTimeField(blank=True, null=True)
    is_completed = models.BooleanField(default=False)
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

todos/forms.py
from django.forms import ModelForm
from django import forms
from .models import Todo

class TodoForm(ModelForm):
    class Meta:        
        model = Todo
        fields = ['title', 'content', 'start_date', 'end_date', 'is_completed', 'user']
        
        labels = {
            'title': '',
            'content': '',
            'start_date': '시작일',
            'end_date': '종료일',
            'is_completed': '완료여부 ',
            'user': '작성자',
        }
        
        widgets = {
            'title': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': '제목을 입력하세요.'}),
            'content': forms.Textarea(
                attrs={'class': 'form-control', 'placeholder': '내용을 입력하세요.', 'rows': 5}),
            'start_date': forms.DateTimeInput(
                attrs={'class': 'form-control', 'type': 'datetime-local'}),
            'end_date': forms.DateTimeInput(
                attrs={'class': 'form-control', 'type': 'datetime-local'}),
            'is_completed': forms.CheckboxInput(
                attrs={'class': 'form-check-input', 'style': 'margin-left: 10px;font-size: 1.2rem;'}),
            'user': forms.Select(
                attrs={'class': 'form-select'}),
        }

todos/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from .models import Todo
from .forms import TodoForm
from calendar import HTMLCalendar
from datetime import datetime
import calendar

class TodoCalendar(HTMLCalendar):
    def __init__(self, year=None, month=None, todos=None):
        self.year = year
        self.month = month
        self.todos = todos
        super(TodoCalendar, self).__init__()

    def formatday(self, day, weekday):
        if day == 0:
            return '<td class="noday bg-light"></td>'
        
        events_html = ""
        if self.todos:
            day_todos = [t for t in self.todos if t.start_date and t.start_date.day == day]
            for t in day_todos:
                events_html += f'<div class="text-truncate"><a href="/apps/todos/detail/{t.id}/" class="badge bg-primary text-white" style="font-size: 0.7rem; display: block; margin-bottom: 2px; {t.is_completed and 'text-decoration: line-through;' or 'text-decoration: none;'}">{t.title[:10]}...</a></div>'
        
        return f'<td class="{self.cssclasses[weekday]} border" style="height: 100px; vertical-align: top; width: 14.28%;"><div class="fw-bold mb-1">{day}</div>{events_html}</td>'

    def formatmonth(self, withyear=True):
        v = super().formatmonth(self.year, self.month, withyear) # type: ignore
        return v.replace('<table border="0" cellpadding="0" cellspacing="0" class="month">', '<table class="table table-bordered text-start">')

def index(request, year=None, month=None):
    if year is None or month is None:
        now = datetime.now()
        year = now.year
        month = now.month

    # Calendar setup
    todos_list = Todo.objects.filter(start_date__year=year, start_date__month=month)
    cal = TodoCalendar(year, month, todos_list).formatmonth(withyear=True)
    
    paginator = Paginator(todos_list, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    # Previous/Next Month Calculation
    prev_month = month - 1
    prev_year = year
    if prev_month == 0:
        prev_month = 12
        prev_year = year - 1

    next_month = month + 1
    next_year = year
    if next_month == 13:
        next_month = 1
        next_year = year + 1

    month_name = list(calendar.month_name)[month]
    time = datetime.now().strftime('%I:%M:%S %p')
    todos = Todo.objects.all().order_by('start_date')
    context = {'cal': cal, 'year': year, 'month': month, 
            'time': time, 'month_name': month_name,
            'page_obj': page_obj, 'today': datetime.today(),
            'prev_year': prev_year, 'prev_month': prev_month,
            'next_year': next_year, 'next_month': next_month,
    }
    return render(request, 'todos/index.html', context )
    
def todo_list(request):
    queryset = Todo.objects.all().order_by('start_date')
    
    search_query = request.GET.get('searched')
    if search_query:
        queryset = queryset.filter(title__icontains=search_query)
    
    paginator = Paginator(queryset, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'todos/todo-list.html', {'page_obj': page_obj})

def create(request):
    if request.method == 'POST':
        form = TodoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('todos:index')
    else:
        form = TodoForm()
    return render(request, 'todos/create.html', {'form': form})

def update(request, todo_id):
    todo = Todo.objects.get(id=todo_id) 
    if request.method == 'POST':
        form = TodoForm(request.POST, instance=todo)
        if form.is_valid():
            form.save()
            return redirect('todos:detail', todo_id=todo.id) # type: ignore
    else:
        form = TodoForm(instance=todo)
    return render(request, 'todos/update.html', {'form': form, 'todo': todo,})

def delete(request, todo_id):
    if request.method == 'POST':
        todo = Todo.objects.get(id=todo_id)
        todo.delete()
        return redirect('todos:index')
    else:
        todo = Todo.objects.get(id=todo_id)
        todo.delete()
        return redirect('todos:index')

def detail(request, todo_id):
    todo = Todo.objects.get(id=todo_id)
    return render(request, 'todos/detail.html', {'todo': todo})

templates/todos/_nav.html
<nav class="navbar navbar-expand-lg bg-light navbar-light py-1 rounded-3 mb-3 border-bottom border-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'todos:index' %}">Dashbord</a>
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'todos:list' %}">Todos</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'todos:create' %}">Create Todo</a>
            </li>
        </ul>
        <form class="d-flex rounded-3" role="search" >
            <input class="form-control me-2 py-1" type="search" placeholder="Search title, content..." name='searched' action="{% url 'todos:list' %}"/>
            <button class="btn btn-outline-success btn-sm py-1" type="submit">Search</button>
        </form>
    </div>
</nav>

templates/todos/create.html
{% extends "base/base.html" %}
{% block title %} Todo 생성 {% endblock %}
{% block content %}
{% include 'todos/_nav.html' %}
<div class="d-flex flex-column justify-content-start align-items-start gap-3">
    <div class="border" style="width: 100%; padding:2rem;margin:auto;">
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}
            <button class="btn btn-success">생성하기</button>
        </form>
        <br>
        <div class="mt-3">
            <a href="{% url 'todos:index' %}" class="btn btn-primary btn-sm">GO LIST</a>
            <a href="javascript:history.back()" class="btn btn-secondary btn-sm">Go Back</a>
        </div>
    </div>
</div>
{% endblock %}

templates/todos/detail.html
{% extends "base/base.html" %}
{% block title %} Todo 상세 {% endblock %}
{% block content %}
{% include 'todos/_nav.html' %}
    <div class="border rounded-3 p-2">
        <div class="d-flex gap-3 align-items-end justify-content-star">
            <h3><a href="{% url 'todos:update' todo.id %}">{{ todo.title }}</a></h3>
            <div class="pb-2">
                <small class="text-muted">on {{ todo.created_at|date:"Y-m-d H:i"}} </small>
                <small class="text-muted">by {{ todo.user.username }} </small>
            </div>
        </div>
        <hr>
        <div>{{ todo.content|safe }} </div>
        <div class="mt-3">
            <a href="{% url 'todos:index' %}" class="btn btn-primary btn-sm">GO LIST</a>
            <a href="javascript:history.back()" class="btn btn-secondary btn-sm">Go Back</a>
        </div>
    </div>
{% endblock %}

templates/todos/home.html
{% extends "base.html" %}
{% block content %}
{% include 'todos/_nav.html' %}
    {% if page_obj %}
    {% for todo in page_obj %}
    <div class="border rounded-3 ps-3">
        <div class="d-flex gap-3 align-items-end justify-content-star mb-0 pb-0">
            <h3><a href="{% url 'todos:update' todo.id %}">{{ todo.title }}</a></h3>
            <div class="pb-2">
                <small class="text-muted">on {{ todo.created_at|date:"Y-m-d H:i"}} </small>
                <small class="text-muted">by {{ todo.user.username }} </small>
            </div>
        </div>
        <hr>
        <div class="mb-2">{{ todo.content|safe }} </div>
    </div>
    <br>
    {% endfor %}
    {% else %}
    <div>할일이 없습니다.</div>
    {% endif %}
{% endblock %}

templates/todos/index.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %} Todos Home {% endblock %}
{% block content %}
<div class="d-flex flex-column">
    <div class="text-center">
        <div class="d-flex gap-2 justify-content-center align-items-center">
            <a href="{% url 'todos:index' prev_year prev_month %}" class="page-link fs-2 pb-3"><i class="bi bi-arrow-left-circle-fill"></i> </a>
            <h1 class="mx-3"> Todos Dashoard </h1>
            <a href="{% url 'todos:index' next_year next_month %}" class="page-link fs-2 pb-3"><i class="bi bi-arrow-right-circle-fill"></i></a>
        </div>
        {% include 'todos/_nav.html' %}
        {{ cal|safe }}
    </div>
    <ul class="my-3">
        {% for todo in page_obj %}
        <li class="py-1">
            <span {% if todo.is_completed %}class="text-decoration-line-through"{% endif %}
            >{{ todo.title }}</span>
            <a href="{% url 'todos:update' todo.id %}"> 수정</a>
            <small class="text-muted">on {{ todo.created_at|date:"Y-m-d H:i"}} </small>
            <small class="text-muted">by {{ todo.user.username }} </small>
        </li>
        {% endfor %}
    </ul>
</div>
<div style="position: fixed; bottom:1rem;text-align:center;width:90%;">Copyright &copy; {{ year }}</div>
{% endblock %}

templates/todos/todo-list.html
{% extends "base/base.html" %}
{% block title %} Todo 목록 {% endblock %}
{% block content %}
{% include 'todos/_nav.html' %}
    {% if page_obj %}
    {% for todo in page_obj %}
    <div class="border rounded-3 ps-3">
        <div class="d-flex gap-3 align-items-end justify-content-star mb-0 pb-0">
            <h3><a href="{% url 'todos:update' todo.id %}"
                {% if todo.is_completed %}class="text-decoration-line-through"{% endif %}
            >{{ todo.title }}</a></h3>
            <div class="pb-2">
                <small class="text-muted">on {{ todo.created_at|date:"Y-m-d H:i"}} </small>
                <small class="text-muted">by {{ todo.user.username }} </small>
            </div>
        </div>
        <hr>
        <div class="mb-2">{{ todo.content|safe }} </div>
    </div>
    <br>
    {% endfor %}
    {% else %}
    <div>할일이 없습니다.</div>
    {% endif %}
{% endblock %}

templates/todos/update.html
{% extends "base/base.html" %}
{% block title %} Todo 수정하기 {% endblock %}
{% block content %}
{% include 'todos/_nav.html' %}
<div class="d-flex flex-column justify-content-start align-items-start gap-3 bg-white rounded-3">
    <div class="border" style="width: 100%; padding:2rem;margin:auto;">
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}
            <button class="btn btn-success btn-sm">수정하기</button>
            <a href="{% url 'todos:delete' todo.id %}" class="btn btn-danger btn-sm" onclick="return confirm('삭제하시게요 ?')">삭제하기</a>
        </form>
    </div>
    <div class="mt-3">
        <a href="{% url 'todos:index' %}" class="btn btn-primary btn-sm">GO LIST</a>
        <a href="javascript:history.back()" class="btn btn-secondary btn-sm">Go Back</a>
    </div>
</div>
{% endblock %}